<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="Images\Banner3.jpg" alt="Banner3" width="100%" height=auto>
      <div class="carousel-caption">
      </div>   
    </div>
    <div class="carousel-item">
      <img src="Images\Banner2.jpg" alt="Banner2" width="100%" height=auto>
      <div class="carousel-caption">
      </div>   
    </div>
    <div class="carousel-item">
      <img src="Images\Banner1.jpg" alt="Banner1" width="100%" height=auto>
      <div class="carousel-caption">
      </div>   
    </div>
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>