<footer>
	<section>
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-3">
					<strong>CONNECT WITH LCCC</strong>
					<span class="icons">
						<a href="https://www.facebook.com/lorainccc">
							<i class="fab fa-facebook-f social"></i>
						</a>
						<a href="https://twitter.com/lorainccc">
							<i class="fab fa-twitter social"></i>
						</a>
						<a href="https://www.linkedin.com/school/lorain-county-community-college/">
							<i class="fab fa-linkedin-in social"></i>
						</a>
						<a href="https://www.instagram.com/lorainccc/">
							<i class="fab fa-instagram social insta"></i></span>
						</a>
					</span>
					<span class="icons">
						<a href="url">
							<i class="fas fa-mobile-alt mobile"></i>
							<strong>MOBILE APP</strong>
						</a>
					</span>
					<span>
						<a href="https://www.lorainccc.edu/website-feedback/?siteurl=https://www.lorainccc.edu/about/">Feedback about this page</a>
					</span>
					<hr class="hide">
				</div>
				<div class="col-sm-3">
					<strong>CONTACT LCCC</strong>
					<p>
						1005 N Abbe Rd
						<br>
						Elyria, OH 44035
						<br>
						1-800-995-LCCC (5222)
						<br>
						or (440) 365-5222
						<br>
						<a href="mailto:info@lorainccc.edu">info@lorainccc.edu</a>
					</p>
					<p>
						<a href="https://www.lorainccc.edu/about/contact-lorain-county-community-college/">Contact LCCC</a>
					</p>
					<hr class="hide">
				</div>
				<div class="col-sm-3">
					<strong> CAMPUS LOCATIONS</strong>
					<span>
						<a href="https://www.lorainccc.edu/about/map-and-directions-to-lccc/">Elyria Campus</a>
						<br>
						<a href="https://www.lorainccc.edu/learning-centers/community-learning-center-at-lorain-high-school/">Community Learning Center at Lorain High</a>
						<br>
						<a href="https://www.lorainccc.edu/learning-centers/lccc-lorain-learning-center-at-city-center/">Lorain Learning Center at City Center</a>
						<br>
						<a href="https://www.lorainccc.edu/learning-centers/lccc-wellington-center/">LCCC Wellington Center</a>
						<br>
						<a href="https://www.lorainccc.edu/learning-centers/university-partnership-ridge-campus/">University Partnership Ridge Campus</a>
						<br>
						<a href="https://www.lorainccc.edu/about/map-and-directions-to-lccc/">Map and Directions</a>
					</span>
					<hr class="hide">
				</div>
				<div class="col-sm-3">
					<strong>QUICK LINKS</strong>
					<span>
						<a href="https://www.lorainccc.edu/up/">University Partnership</a>
						<br>
						<a href="https://www.lorainccc.edu/athletics/">Athletics</a>
						<br>
						<a href="https://www.lorainccc.edu/human-resources/employment-opportunities-at-lccc/">Employment Opportunities at LCCC</a>
						<br>
						<a href="https://www.lorainccc.edu/veterans/">Veterans Services</a>
						<br>
						<a href="http://www.lcccfoundation.org/">Giving</a>
						<br>
						<a href="https://www.lorainccc.edu/policies/campus-policies/web-site-privacy-policy/">Privacy Policy</a>
						<br>
						<a href="https://www.lorainccc.edu/getting-started/campus-visitation-days/">Visit LCCC</a>
					</span>
				</div>
			</div>
		</div>
		<hr>
		<p class="stamp">Created by: Gage Riley</p>
	</section>
</footer>